---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-capstone
  namespace: wordpress-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-capstone
  template:
    metadata:
      labels:
        app: wordpress-capstone
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 33
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: wordpress
          image: wordpress:6.9.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["CHOWN", "SETGID", "SETUID", "NET_BIND_SERVICE"]
          volumeMounts:
            - name: wordpress-capstone-storage
              mountPath: /var/www/html
          envFrom:
            - configMapRef:
                name: wordpress-capstone-env
            - secretRef:
                name: wordpress-capstone-secret
      volumes:
        - name: wordpress-capstone-storage
          persistentVolumeClaim:
            claimName: wordpress-capstone-pvc
