apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/authentik/
  - ./configmap.yaml
  - ./database.yaml
  - ./secrets.yaml
configMapGenerator:
  - name: authentik-values
    files:
      - ./values.yaml
