authentik:
  redis:
    host: "dragonfly-redis-master.dragonfly-system.svc.cluster.local"
    port: 6379
  env:
    AUTHENTIK_REDIS__PASSWORD:
      valueFrom:
      secretKeyRef:
        name: dragonfly-redis
        namespace: dragonfly-system
        key: redis-password
