agent: false
operator:
  enabled: false
cni:
  install: false
gatewayAPI:
  secretsNamespace:
    create: false
    sync: false
hubble:
  enabled: false
  relay:
    enabled: false
  ui:
    enabled: true
    standalone:
      enabled: true
    fullnameOverride: hubble-ui
    backend:
      extraEnv:
        - name: FLOWS_API_ADDR
          value: "hubble-relay.kube-system.svc.cluster.local:80"
