apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix
  namespace: kiwix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwix
  template:
    metadata:
      labels:
        app: kiwix
    spec:
      securityContext:
        fsGroup: 101
        runAsUser: 100
        runAsGroup: 101
      containers:
        - name: kiwix
          image: ghcr.io/kiwix/kiwix-serve:3.8.1
          args:
            - '*.zim'
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: media-zim
              mountPath: /data
      volumes:
        - name: media-zim
          nfs:
            # server: 10.0.150.100
            server: 10.0.50.100 # Temporary fix
            path: /mnt/DataVault/Media/ZIM
            readOnly: true
