apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dragonfly-system
resources:
  - ../../base/dragonfly/
configMapGenerator:
  - name: dragonfly-values
    files:
      - ./values.yaml
