---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-gateway-cert
  namespace: public-gateway
spec:
  secretName: public-gateway-tls
  dnsNames:
    - "*.collazoirizarry.xyz"
  issuerRef:
    name: clusterissuer-racknerd
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smartrenergy-cert
  namespace: public-gateway
spec:
  secretName: smartrenergy-tls
  dnsNames:
    - "smartrenergy.com"
  issuerRef:
    name: clusterissuer-racknerd
    kind: ClusterIssuer
    group: cert-manager.io
