---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-gateway-cert
  namespace: public-gateway
spec:
  secretName: public-gateway-tls
  dnsNames:
    - "*.collazoirizarry.xyz"
  issuerRef:
    name: clusterissuer-staging
    kind: ClusterIssuer
    group: cert-manager.io
