---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: https-gateway
  namespace: public-gateway
  annotations:
    cert-manager.io/cluster-issuer: clusterissuer-racknerd
spec:
  addresses:
    - type: IPAddress
      value: 23.95.171.104
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.collazoirizarry.xyz"
      tls:
        certificateRefs:
          - kind: Secret
            name: public-gateway-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              public-gateway: "true"
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.collazoirizarry.xyz"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              public-gateway: "true"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-gateway
  namespace: public-gateway
spec:
  addresses:
    - type: IPAddress
      value: 23.95.171.99
  gatewayClassName: cilium
  listeners:
    - name: tls-passthrough
      protocol: TLS
      port: 8443
      hostname: "unifi-test.collazoirizarry.xyz"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              public-gateway: "true"
    - name: unifi-inform
      protocol: HTTP
      port: 8080
      hostname: "unifi-test.collazoirizarry.xyz"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              public-gateway: "true"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: unifi-guest-gateway
  namespace: public-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: unifi-guest-portal
      protocol: TLS
      port: 8843
      hostname: "unifi-test.collazoirizarry.xyz"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              public-gateway: "true"
