---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  namespace: public-gateway
  annotations:
    cert-manager.io/cluster-issuer=clusterissuer-racknerd
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.collazoirizarry.xyz"
      tls:
        certificateRefs:
          - kind: Secret
            name: public-gateway-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              public-gateway: "true"
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.collazoirizarry.xyz"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              public-gateway: "true"
