---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: gateway-policy
  # namespace: kube-system
spec:
  serviceSelector:
    matchExpressions:
      - key: "gateway.networking.k8s.io/gateway-name"
        operator: Exists
  externalIPs: true
  loadBalancerIPs: true
