---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lan-gateway-cert
  namespace: lan-gateway
spec:
  secretName: lan-gateway-tls
  dnsNames:
    - "*.raymondcollazo.com"
  issuerRef:
    name: clusterissuer-staging
    kind: ClusterIssuer
    group: cert-manager.io
