apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ippool.yaml/
  - ./l2policy.yaml/
  - ./gateway.yaml
  - ./certificate.yaml
  - ./namespace.yaml
  - ./cilium-secrets-rbac.yaml
