---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-smartrenergy-env
  namespace: wordpress-smartrenergy
data:
  WORDPRESS_DB_HOST: "wordpress-smartrenergy-db.wordpress-smartrenergy.svc.cluster.local"
  WORDPRESS_DB_NAME: "wordpress-smartrenergy"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_TABLE_PREFIX: "wp_"
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_HOME', 'https://smartrenergy.com');
    define('WP_SITEURL', 'https://smartrenergy.com');
    if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
        $_SERVER['HTTPS'] = 'on';
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-smartrenergy-php-ini
  namespace: wordpress-smartrenergy
data:
  uploads.ini: |
    upload_max_filesize = 512M
    post_max_size = 512M
    memory_limit = 256M
    max_execution_time = 300
