apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/wordpress/smartrenergy/
  - configmap.yaml
  - secrets.yaml
  - route.yaml
patches:
  - path: patches.yaml
