apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actualbudget
resources:
  - ../../base/actualbudget/
  - ./certificate.yaml
  - ./gateway.yaml
  - ./secrets.yaml
configMapGenerator:
  - name: actualbudget-values
    files:
      - ./values.yaml
