login:
  method: "openid"
  openid:
    enforce: true
    providerName: "Authentik
    discoveryUrl: "https://auth.raymondcollazo.com/application/o/actual/"
    existingSecret:
      name: "actualbudget-openid-secret"
      clientIdKey: "clientId"
      clientSecretKey: "clientSecret"
