apiVersion: v1
data:
    FirstName: ENC[AES256_GCM,data:EKmMH+hIskM=,iv:oJ2bum7aDQPkr7SBizwGwE7CL3r/+1UwQPEMU6Zlux8=,tag:mvuaLJ7fcI/COyYBzUxW7A==,type:str]
    LastName: ENC[AES256_GCM,data:jyqIcOBbgXFyV1ZY,iv:XpPzMc9xWQsVKlybp49dAJqfzC4ODzuiOA/HAMw/wN8=,tag:Z2dNxfutyAeiVITQ50ODCA==,type:str]
    Password: ENC[AES256_GCM,data:vGcWWLygVmsi9qUe3g08BHdaANW4oEKVcN0l331TioCGtHnKWMAGEndZym7HiYuDJsDUp+jcCKVV3fkt3yQWwboUy0XXBijGQLnBkMRaPW8fv8wrDfYcWT6O7lNHh7u5bL+UQXW6+BZbE8D4Y5yMpb+U0GppeyPf2haWnmzfCBLWc2YtcJrZBGfJBcxnprT1RbqGbBH4hzUQiWj5PSxVZ/iIzFjX5oKFslPoeg==,iv:ao1OieVyb8CZhWzC8C2wvDlpd/C7AHaDrXNbuwOe/Ao=,tag:cGVL8BNBzRPnrIDC2AZoEg==,type:str]
    Username: ENC[AES256_GCM,data:62UtIYK8ujY=,iv:TjpLIy6B1rErFYSICM3qpimlpMis62x4KORs09M7i4c=,tag:uColWsyYEliveqQwXyx/3g==,type:str]
kind: Secret
metadata:
    name: ops-manager-cred
    namespace: mongodb
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubkRyNElXVWlyWE1oRzJ4
            dnJDR2xHT2d1dnJjbVlOYXB6Z0hqUExwR0hZClJXcUhFMHJLL1B0eWdNQ2lOS0Yz
            S0xncDdDM2xUaE5kTkt1bG5oK1hIczQKLS0tIG9PTEVncDVaWi9uQXBBVks5OTR4
            MFl4YnJIT3hXY1NmYWRLZGVTUmJVdDgKdBwyRd3/bKeVxHwWhNWTsKYDij26TPyY
            +r36DsN//OL3cWaoFkxL3v53WgGN04f6Bl8itvTy/S2tmbDtHq1hDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T08:43:08Z"
    mac: ENC[AES256_GCM,data:5GUOb1KiiTVLc/5CkF24vGQyOuHdQkSCss9th/RpccA9eoYyN9z8XSyFB825/dEJLz7J9mN8oJh27/+6YdX5CMNYskrIE4/5BNOYjsnygGHRhXJLggLaeaN1RdZo//1YUAqCDsi2wW9rgf8inKtDuxTgM3Zz2IEKRfYTWCenQAQ=,iv:T0dAWasKxo4DlqQrJEKCir3NhIi8eZShDR1qXohd8CY=,tag:6JgH8zpJmhMqulW1QG3XZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
