apiVersion: v1
data:
    FirstName: ENC[AES256_GCM,data:i7SaJZSO4+E=,iv:NPpj/+652k9JB8BDKkHle5xJAS8jLrWCvWnfn/uqb8I=,tag:OcEPkeh8ugWhOkvm9BofDw==,type:str]
    LastName: ENC[AES256_GCM,data:lZtyGIvNz2WgVYjf,iv:OfJBU2Dwir6NAYq8XdwMe5PO/iTuI5Y2Q2onWAMGgDA=,tag:wVoDmR4z9p6f/bHfdhmH7A==,type:str]
    Password: ENC[AES256_GCM,data:fcb5yt8Zv16otK8hSSwk5n07gnrSMEuSqSA1K1ymQxadZuIcqV7X34zvstPJ1QQ2Jph4HybnwvfR3A7GDEImz9aE+q6eIUYMSLm+V4zZgs6hehCoxRR95/XSS2lI0sMgRzNMh991oJlQA2K65EP472/rKigk5d2uyLnQ1u5Ldvz7h9qzV/AnE4kA1fH6JAcZcPemzZnPjNvubypSM3ThL1fsq2Hx0kxtM7HL1Q==,iv:7FRscrSM6ZJEUaMu8YOI9kxJ2a5+tNjPakWNeUoJSlE=,tag:4IVdctECpOhFT9um3uaHiA==,type:str]
    Username: ENC[AES256_GCM,data:pJagObpnwto=,iv:g3Njp1qGhJfXASIFYkzwxAqfNKF0vewA0Hbdi54GPK8=,tag:2wtviJ31TVDbPtm3B4EPuQ==,type:str]
kind: Secret
metadata:
    name: ops-manager-cred
    namespace: mongodb
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb1NHa1hRS2hGKzV6Sll1
            QTlqR3hxM1NHb3dkVm1xdTdOUDMvUEpHWlVNCnJYeThXdmQrZG1ET2FpVW9vVXRL
            U3ZBWDg4czAxZnlJeEFJTTBwL3kxTXcKLS0tIGlBV1l6R2hHb09uTjJFZzdrNWRp
            cWRjTjV5ZENKOG51SFMxMHdrQk43T0EKEe1BRazEt2jN3Xh2fyb5vLcoVnkNVpPF
            efsW/QgVJuIGn25zUTtqS9qgqoWCgX25eBhxJPb/weEECF574j7WYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T08:58:00Z"
    mac: ENC[AES256_GCM,data:jtIwIEtwe+ya4lZ0i5sd2tiZZdz0Kfjqm9eSCBEM7QYoHRd7XtvBjIRefujE0EnQzltDyDbil0D5m+3bxr7zHaAaHTYGpJCR1XANWyxk9zhK70ph9Gr7zAN3NOti4ZBHVORn0n/Jgcglhz2mNYRHdREIckAy/Q7OBFBLkCY54+A=,iv:KTlW/KJ01l9sqJIbybQrF7rnb6YmKhtiYCDAbePYYtU=,tag:GHmS5dmrvfl2nSujJmRXwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
