apiVersion: v1
data:
    FirstName: ENC[AES256_GCM,data:p0oOcGV6lSA=,iv:mD15Y1q/+a9TQWjVK+5ExpglaiGzQdkfUxejml21CIg=,tag:i+lzeZDF0yiz8ds4437j2g==,type:str]
    LastName: ENC[AES256_GCM,data:oHmRNGKCxVIy86QE,iv:yBQz4iZjOTelUMi7YTrseZJCYWLiE6h8EM1tyBgFGrU=,tag:s3cJq5BfWyXVFgLiMPrftg==,type:str]
    Password: ENC[AES256_GCM,data:YZQgMtdhVe/n+Z7Y7NhZjgkHyLZgS1P10ofJ7SDXbyWuZjZl4tnCZvGSXqw=,iv:pY0HJTrj+fiYEfyA9DApCIsAmFSLc+ed1gJTPWWfMgo=,tag:bUr17fSQNqsmHnznHs8GNA==,type:str]
    Username: ENC[AES256_GCM,data:1UR6U3jsJAg=,iv:gZuR2BsEmjPCZXPjClNK/Dj8W8ezfqWh70mvNX8eRJg=,tag:+K6jO4Z4lTxIBueElyKqrQ==,type:str]
kind: Secret
metadata:
    name: ops-manager-cred
    namespace: mongodb
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsT1JSSDI5d0Y5SnpEclJG
            d1Q3cHJlUjR0KytCczVEQm16ZkI0aC9SeEVrClB2QVN5M2NaZnlEY0Z2cy9KVk1h
            eGxUaVd4Nks0N2lMNzJvY3I4bUc5cXMKLS0tIEZwZGpmNGI0eW1ZdWtxZGFiOG5R
            cUd5Tm8yRXVOY2VwdkdFaGF2cWlWUDAKvJE6jVz8i4n403tGI4FdZZ49Tx7Ucm01
            kNz2SbFehVKx63/1Uo/15Si5d4cNy2j2stdwMSmGGtXhzoBAejIuRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T08:36:21Z"
    mac: ENC[AES256_GCM,data:RQISvuyujYvXxyFZQEHN+cptDNzWaRErqEB6CfSiwNVjiEY2tngmrnACinb2boMwvi/s/4JKY/k8ZHgHRD2g8loeXpoBlt1Bzndz/WEz59/b6RWeQnF6X4Nq6YI8n3YzNbGrn5BP5ajLpMJF2ONp9YE/WnbrA9mmH7psZlHpGBY=,iv:GrhE3FG5SZ0vdZtCeYmfvMfqhYsP+ZBfMcGpSxWEOGo=,tag:HJlQkoSbtzBBeYT/LvD+FA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
