---
apiVersion: v1
data:
    Password: ENC[AES256_GCM,data:RkDyN69B3aq3VyJnve/73pG/p123wObWy8PDeFOyYGd/akD2J1y618+famU=,iv:wSP0gCS5ZqTEULX4kOrMMksp/k/D07Uif43mp/1zX5s=,tag:dVy3VM0vcKTzhcjpH2TU3g==,type:str]
    Username: ENC[AES256_GCM,data:mFAnrqdXFDg=,iv:E9P2mZi0Wn/7nzHbAQEyUgzNHoo/9X8fprufL9gflWg=,tag:LEsAEtOv+WLdC7zRCVOWkg==,type:str]
kind: Secret
metadata:
    name: ops-manager-cred
    namespace: mongodb
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaERXb1IvalR3QVhBYWRZ
            aGprbFl1c2wrNlVoaktUYjFSZzQ2TFlzWDA4ClZSTXRDZldObU11MlZ4cHF6SmNE
            QWpzQXFvUWdiVCtEa3BPNzNXSWx5ak0KLS0tIG5iY2NWNm9jc0xFZlp4ZlRHRlNK
            SGNndFVDdmVZUG9CckRZK3VqTHZ3cEEK+iOsNJEUxix04j/UlciYcaB7IlmgZWEb
            KfZkOTSOxihYajjRQLqsHoMvdPZlemg4jXXACHviT0S8UR73C+3iFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T07:51:40Z"
    mac: ENC[AES256_GCM,data:UDWuuGs456Yz/BMty6zKCJHE91rxzkS5SYKfImwL7n+p+qM3NM8G46Dpe/76Id7opJDT/Pmvff1E+v3zjOvYDDDjwH14QK00B6KnFXuPuXwGhxKdQeO3CSSjoRmOGoDnVpqIG77LBnJNku/H+AR4O5QBGbMNEPoCqoKRj5nvO9I=,iv:sVN0GATtefGc6dw5fQT3ukrfNa8RNK2DERV9i1M9Vlk=,tag:JGDbxpJfKncZnd2LFHWV1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
