---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: opsmanager
  namespace: mongodb
spec:
  replicas: 1
  version: 8.0.12
  adminCredentials: ops-manager-cred
  externalConnectivity:
    type: ClusterIP
  applicationDatabase:
    topology: SingleCluster
    members: 3
    version: 8.0.0
