apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - ../../base/n8n/
  - ./database.yaml
  - ./route.yaml
  - ./secrets.yaml

configMapGenerator:
  - name: n8n-values
    files:
      - values.yaml=values.yaml
