kubeProxyReplacement: true
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 6443

# gatewayAPI:
#   enabled: true
#   enableAlpn: true
#   enableAppProtocol: true
#   gatewayClass:
#     create: "true"
#   hostNetwork:
#     enabled: true
#
# envoyConfig:
#   enabled: true
#   hostNetwork:
#     enabled: true
#
# envoy:
#   enabled: true
#   securityContext:
#     capabilities:
#       envoy:
#         - NET_ADMIN
#         - SYS_ADMIN
#         - NET_BIND_SERVICE
#       keepCapNetBindService: true
#
operator:
  replicas: 1
hubble:
  relay:
    enabled: true
