---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-network-application
  namespace: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-network-application
  template:
    metadata:
      labels:
        app: unifi-network-application
      annotations:
        secret.reloader.stakater.com/reload: "unifi-tls"
    spec:
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
        - name: unifi-network-application
          image: lscr.io/linuxserver/unifi-network-application:10.1.85
          ports:
            - containerPort: 8443
            - containerPort: 8080
            - containerPort: 8843
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: unifi-config
              mountPath: /config
            - name: unifi-tls
              mountPath: /config/keys/cert.crt
              subPath: tls.crt
            - name: unifi-tls
              mountPath: /config/keys/privkey.pem
              subPath: tls.key
            - name: unifi-cert-import
              mountPath: /custom-cont-init.d/import-cert.sh
              subPath: import-cert.sh
          envFrom:
            - configMapRef:
                name: unifi-env
            - secretRef:
                name: unifi-secret
      volumes:
        - name: unifi-config
          persistentVolumeClaim:
            claimName: unifi-config-pvc
        - name: unifi-tls
          secret:
            secretName: unifi-tls
        - name: unifi-cert-import
          configMap:
            name: unifi-cert-import
            defaultMode: 0755
