---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-network-application
  namespace: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-network-application
  template:
    metadata:
      labels:
        app: unifi-network-application
    spec:
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
        - name: unifi-network-application
          image: lscr.io/linuxserver/unifi-network-application:10.0.162
          ports:
            - containerPort: 8443
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: unifi-config
              mountPath: /config
          envFrom:
            - configMapRef:
                name: unifi-env
            - secretRef:
                name: unifi-secret
      volumes:
        - name: unifi-config
          persistentVolumeClaim:
            claimName: unifi-config-pvc
