---
apiVersion: v1
kind: Service
metadata:
  name: unifi-svc
  namespace: unifi
spec:
  ports:
    - name: https
      port: 8443
    - name: http-inform
      port: 8080
    - name: guest-portal
      port: 8843
  selector:
    app: unifi-network-application
  type: ClusterIP
