apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-racknerd
spec:
  acme:
    email: acme.fpdj9@simplelogin.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: clusterissuer-racknerd-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
