---
apiVersion: v1
data:
    token: ENC[AES256_GCM,data:FafYtw8QdBzX8bxNBzXPb20rh6kvD77bfKCRqouUX5p0goBnt2dJUKYPufExL1C/Ivswgobwd80=,iv:up3nWumes2ElYZ3AfuSYk+LsZSmGXK9OZ3eMH2/K/3c=,tag:zVRo6NANe1H3k/drMhxdJg==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRHBFTGRZTG4rejVLMmlQ
            cFZLdFRZMDNsV3BhMnF3bHB6dGlybHpEemdzCnRrY2w2VGlCYVJSTGdnUlgxSmxp
            M3dtSmhFK0JXazFHZDBST0Y3N1dkVmcKLS0tIFVkRExQSHhwVEFXUVM0K2N2VTBt
            MGVrVDdsZjdqWVZQYzVqRXlPODhTZWsKAofcki5GeP8Ra7/gLF5wNg5FWb/H7IE4
            kKb71JUvjqJQ9x5iBgvOdzHHGT9FM6Oc4Rlaa6wp5cO4ffXPlFXzPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T21:16:43Z"
    mac: ENC[AES256_GCM,data:2IUzAakjGp9i6Jgi2C7GAxwVUYGKAA5Q5h+6D5X3ytHeRKb+3hUOY3Sss5yMYCz7EycYqfYR1JK5BCT0SvhFXt7SM677ZXgLlGhB7AqbOKT9wwMD4ezn31+XXyhxQsr5QYyeV9ZnxUvAGN3FXm8ydUoROYkHMm7DaTWcgZ/fSro=,iv:4z9HbQrWh7hTKbjb+PEDvTOnJHIr4PeKKPxwKRw3xM0=,tag:PgpPlSEXLlLmrfwr95HQOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
