apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik/
  - ./cert-manager/
  - ./cilium/
  - ./cloudflared/
  - ./cloudnative-pg/
  - ./dragonfly/
  - ./gateway-api/
  - ./renovate/
  - ./rook-ceph/
