---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-smartrenergy-svc
  namespace: wordpress-smartrenergy
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-smartrenergy
  type: ClusterIP
